### ISSUE TITLE
How can generate all main controllers routes

### ISSUE THREAD

**Issue by GAMITG** [mdmsoft/yii2-admin#106]
Good afternoon,

I have use yii2-admin, in that all module's controllers routes is already or automatically generated but how can i generate all main controller's routes.  
In RouteController has no generate action for generate routes but Route/view has generate view file so, how can i use that generate.php view file.

**Comment by akhildar** [comment]
Though I am adding routes, Yii2-admin is not blocking other users.

my configuration is:

'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
            'layout' => 'left-menu',
            'as access' => [
                'class' => 'mdm\admin\components\AccessControl',
                'allowActions'=>[

                ]
            ],
            'controllerMap' => [
                'assignment' => [
                    'class' => 'mdm\admin\controllers\AssignmentController',
                    'userClassName' => 'app\models\Users'
                ]
            ]
        ]
    ],

**Comment by mdmunir** [comment]
@akhildar `'as access'` is belong to application (root config) not belong to module

**Comment by girnarsoftashutosh** [comment]
how to assign routes to admin as well as author so that admin can update any post but author can update only own post

**Comment by MuhammedSami** [comment]
![Capture d’écran 2019-10-15 à 11 30 18](https://user-images.githubusercontent.com/45762520/66814412-37397000-ef3f-11e9-8f9b-6fa5f35dc010.png)

Hello dear yii2-admin contributor, thank you for this greate extension.
My problem is: I could successfully add the module to my config now a you see, I got the visuel but no data seem to be showing. I have only one role in DB which is Admin role that has a child like '/*' but I get nothing visuel related to this item ?

 Any help will be appreciated. thanks
