### ISSUE TITLE
Add New Rules

### ISSUE THREAD

**Issue by abhi1693** [mdmsoft/yii2-admin#113]
I'm using the advanced yii template. I've configured it properly. I'm using DbManager as the class in the authManager section. I get an error whenever I create a new rule. 
Error:   Unknown class: yii\rbac\Rule

How to solve this?

**Comment by mdmunir** [comment]
Check your framework installation. Is file `vendor/yiisoft/yii2/rbac/Rule` exists?

**Comment by abhi1693** [comment]
yes

**Comment by abhi1693** [comment]
![image](https://cloud.githubusercontent.com/assets/5083532/5606510/6eda0e94-9458-11e4-8d8d-a1dec38fa6bf.png)

**Comment by abhi1693** [comment]
I'm probably getting this error because 'Rule' is an abstract class and we cannot instantiate it. Could this be the reason of this error?

**Comment by arrhkm** [comment]
It same to me, plss help me ...
