### ISSUE TITLE
Extend Layout

### ISSUE THREAD

**Issue by abhi1693** [mdmsoft/yii2-admin#116]
Is there a way to extend the layout so that I can customize to my own needs?

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/yii-base-module.html#$layout-detail

**Comment by abhi1693** [comment]
I think you didn't get my question. I want to extent your views to implement my own custom theme. How can I achieve that? Also how can I extent your AdminAsset?

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/yii-base-theme.html
```php
'pathMap' => [
    '@mdm/admin/views' => '@your/theme/views'
]
```
