### ISSUE TITLE
Wrong urls are being generated in routes/menu

### ISSUE THREAD

**Issue by kurrata** [mdmsoft/yii2-admin#119]
I have "File" controler and it has 
```php
public function actionVsaa_import() {
//...
}
```
admin/route page generates this action as "/file/vsaa-import".
As result of this during menu creation when you use this route it generate menu with "/file/vsaa-import" url not "/file/vsaa_import"

**Comment by mdmunir** [comment]
when you call from browser `?r=file/vsaa_import`, is it work?

**Comment by kurrata** [comment]
yes, the url itself works. admin module just generates wrong route

**Comment by mdmunir** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#43-methods
I am not sure underscore is allowed for method name. Can you ask this to Yii2 official issue? If they said OK, i will fix it.

**Comment by mdmunir** [comment]
I am not sure to fix it. Method name should like `actionVsaaImport()`.
Another way, you can create route that you need manually.
