### ISSUE TITLE
site/logout Forbidden (#403)

### ISSUE THREAD

**Issue by liyunfang** [mdmsoft/yii2-admin#120]
siteController            [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],

result:
site/logout Forbidden (#403)

**Comment by mdmunir** [comment]
Add `site/logout` to `AccessControl::$allowActions`

**Comment by liyunfang** [comment]
update your

**Comment by liyunfang** [comment]
update your

**Comment by liyunfang** [comment]
update your AccessControl   can support behaviors



   /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $actionId = $action->getUniqueId();
        $user = $this->user;
        if ($user->can('/' . $actionId)) {
            return true;
        }
        $obj = $action->controller;
        
        if(isset($obj->rules))
        {
            $rules = [];
            $ruleConfig = ['class' => 'yii\filters\AccessRule'];
            foreach ($obj->rules as $i => $rule) {
                if (is_array($rule->actions)) {
                    $rules[$i] = $rule;//Yii::createObject(array_merge($ruleConfig, $rule));
                }
            }
            $request = Yii::$app->getRequest();
             /* @var $rule AccessRule */
             foreach ($rules as $rule) {
                 if ($allow = $rule->allows($action, $user, $request)) {
                     return true;
                 } elseif ($allow === false) {
                     if (isset($rule->denyCallback)) {
                         call_user_func($rule->denyCallback, $rule, $action);
                     } elseif (isset($obj->denyCallback)) {
                         call_user_func($obj->denyCallback, $rule, $action);
                     } else {
                         $this->denyAccess($user);
                     }
                     return false;
                 }
             }
        }

        do {
            if ($user->can('/' . ltrim($obj->getUniqueId() . '/*', '/'))) {
                return true;
            }
            $obj = $obj->module;
        } while ($obj !== null);

        if (isset($this->denyCallback)) {
            call_user_func($obj->denyCallback, null, $action);
        }
        else
        {
            $this->denyAccess($user);
        }

    }
