### ISSUE TITLE
XSS bug

### ISSUE THREAD

**Issue by korshak** [mdmsoft/yii2-admin#121]
Register new user with name:
```
<script>alert('hi')</script>fg<a href="
```

 go to /admin/assignment
 edit created user

(x) Alert is shown

**Comment by mdmunir** [comment]
?

**Comment by korshak** [comment]
XSS works when you are trying to assigning role to user.

**Comment by mdmunir** [comment]
Sorry, what the issue? Please elaborate a bit more.

**Comment by korshak** [comment]
I create user with username 
```
<script>alert('hi')</script>fg<a href="
```
It works well in my yii2 aplication, but I see alert on /admin/assignment/view page. It's bug.

**Comment by marsuboss** [comment]
How you can to create this name (~38 characters) in the column "username" with size 25 characters maximum ?

**Comment by marsuboss** [comment]
I reproduce and i confirm this problem
