### ISSUE TITLE
classname

### ISSUE THREAD

**Issue by andreymecheva** [mdmsoft/yii2-admin#122]
Hi, please help me with this:

When i try create a Rule <code>frontend/web/index.php/admin/rule/create</code>.

I dont known what mean <b>classname</b>. Where I create it, or where i find it.

Unknown Class: *****

Sorry by my english.

**Comment by mdmunir** [comment]
Please read this http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-rules

**Comment by andreymecheva** [comment]
Sorry, but i cant understand.

I create a file with all the rules?
I use the class <code> rules </code> in  model?
in what file create this code?

**Comment by andreymecheva** [comment]
I find the answer:

1. In <code>/common</code> create <code>rbac</code> folder.
2. Create <code>UserRoleRule.php</code> file in <code>/common/rbac</code>.
3. in field <i>classname</i> set <b>coomon\rbac\UserRoleRule</b>

**Comment by dungphanxuan** [comment]
Hello @andreymecheva , i have app and use rbac to manager access control. I create roles and assign to user. And each roles i manager by data. That data will store ruler infor to manager

Example:
  i have roles admin with data [ 'controller_name' =>['list action access']...]
So when user access some action and controller. Like card/create. So i will check roler as user and data has controller name is card and action is create. If it ok, i will allow to access action in behavior method. 
It simple. do you thing it ok, and can you suggest me some method to manager app good?

**Comment by NestorAcevedo** [comment]
Uhm that does not work for me. I have created the file class under the same path but I still receive the class not found error. 

Sorry if is too late but I can't achieve this.
