### ISSUE TITLE
Getting unknown property: common\models\User::user_id

### ISSUE THREAD

**Issue by ipppinto** [mdmsoft/yii2-admin#124]
I have this problem in admin/assignment/view?id=1.

 in /home2/ipinto/public_html/cim-cc/vendor/mdmsoft/yii2-admin/views/assignment/view.php – yii\db\BaseActiveRecord::__get('user_id') at line 46

Thanks

**Comment by camelsoft** [comment]
set  ==> 'idField' => 'id', // id field of model User
not ==> 'idField' => 'user_id', // id field of model User

**Comment by ipppinto** [comment]
In mdmsoft/yii2-admin/views/assignment/view.php I have 'idField' => 'id'. Or I have to change this in another file?

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-admin#customizing-controller
Leave `controllerMap` empty until you **need** to change it.

**Comment by ipppinto** [comment]
Ok. Thanks
