### ISSUE TITLE
Navigation Menu Tree

### ISSUE THREAD

**Issue by RGTimothy** [mdmsoft/yii2-admin#127]
How can i add navigation menu tree like the following schema from yii2-admin menu : 

<pre>
Member Menu
          |________Request
          |________Report
                      |__________Request Report
                      |__________Jobs Report
</pre>

I have no idea how to make this navbar menu with parents & order configuration in yii2-admin. Thanks.

**Comment by mdmunir** [comment]
```php
echo Nav::widget([
    'items' => MenuHelper::getAssignedMenu(Yii::$app->user->id)
]);
```

**Comment by RGTimothy** [comment]
It was not about the widget. I've already used that code. What i need to know is when we open the yii2-admin menu like picture below, what do we have to fill on the parents & order textbox to make 3 layer navbar menu?
![screenshot 2015-01-29 09 39 09](https://cloud.githubusercontent.com/assets/3026828/5951482/ded6342a-a79a-11e4-8433-660fbed03762.png)

**Comment by mdmunir** [comment]
- Create menu with name `Member Menu` and parent name empty.
- Create menu with name `Request` and parent name `Member Menu`.
- Create menu with name `Report` and parent name `Member Menu`.
- etc

**Comment by RGTimothy** [comment]
Yes I was able to do that, but only for 1 maximum child menu. But how to add those 3rd layer menu  (Request Report & Jobs Report)? I tried to add the child menu for "Report" with your guidance and nothing happened. Is it possible to do that?

**Comment by mdmunir** [comment]
> I tried to add the child menu for "Report" with your guidance and nothing happened. Is it possible to do that?

What you mean "nothing happened"? You can do that. no limit hierarcy.

**Comment by RGTimothy** [comment]
Please kindly check these sequential picture below (Menu "Grand Child 1" doesn't appeared): 
![screenshot 2015-01-29 16 48 01](https://cloud.githubusercontent.com/assets/3026828/5955614/41978c58-a7d7-11e4-85ce-ab9273170448.png)
![screenshot 2015-01-29 16 48 50](https://cloud.githubusercontent.com/assets/3026828/5955619/47320490-a7d7-11e4-8776-6b0c5bf5fcd9.png)
![screenshot 2015-01-29 16 50 04](https://cloud.githubusercontent.com/assets/3026828/5955622/4b65e9c8-a7d7-11e4-9d7a-dcd0821e9a23.png)
![screenshot 2015-01-29 16 50 22](https://cloud.githubusercontent.com/assets/3026828/5955625/51b95058-a7d7-11e4-8a09-4a7d6ac72329.png)

**Comment by mdmunir** [comment]
This limitasion of Nav widget, not this extension. You should use other widget.
