### ISSUE TITLE
move the module to modules folder

### ISSUE THREAD

**Issue by hoa2ng** [mdmsoft/yii2-admin#128]
Hi,
I need to add some controllers in the module, so I want to move it to modules folder in yii2 basic template. So I need to change all namespace ?

Could you guys please help me?

Thanks in advance.

**Comment by mdmunir** [comment]
Up to you. I am not sure its a good practice.
You can add controller to module via `controllerMap`.

```php
'controllerMap'=>[
    'yourctrl'=>[
        'class'=>'path\to\YourController',
        
    ]
]
```

**Comment by hoa2ng** [comment]
yes, I tried. but it seems this is not working
I have to change all namespaces of all models, controllers, helpers, assets :(
