### ISSUE TITLE
How to check user can access controller/action in yii2

### ISSUE THREAD

**Issue by noppakun** [mdmsoft/yii2-admin#130]
In yii v.1.x can use  Yii::app()->user->checkAccess('customer/list') ,
but it not work  in yii2,
I try to use  Yii::app()->user->can()   it work only for permission , not work for cortroller/action

**Comment by mdmunir** [comment]
- In Yii1 its also doesnt work for controller/action.
- Its not yii2-admin issue. You should submit this issue to Yii2.
