### ISSUE TITLE
how validate permissions in a menu in yii2 'visible'=>Yii::$app()->user->checkAccess(Yii::$app()->user->id,"/admin/*")

### ISSUE THREAD

**Issue by missjewel** [mdmsoft/yii2-admin#137]
I am trying validate permissions in a menu with  Nav::widget like
 'visible'=>Yii::$app()->user->checkAccess(Yii::$app()->user->id,"/admin/*") 

but give a error: Function name must be a string

**Comment by mdmunir** [comment]
`Yii::$app->user` not `Yii::$app()->user`

**Comment by missjewel** [comment]
thanks, but now give a error: Calling unknown method: yii\web\User::checkAccess()

**Comment by missjewel** [comment]
I am trying and work : Yii::$app->user->can("/admin/* ")
