### ISSUE TITLE
params variable in Rule's execute() method

### ISSUE THREAD

**Issue by pc-carm** [mdmsoft/yii2-admin#142]
I'm trying to implement this: users with 'admin' role can view, edit and delete other 'admin' users. 'manager' users can view, edit and delete any user except 'admins'. For this, I have role 'admin' and role 'manager'. Both roles have permission to access user's index, create, view, update and delete actions, generated by gii's CRUD, in separate permission items.
For view, update and delete permissions, I assigned a Rule with this execute method:
```php
    public function execute($user, $item, $params) {
        $usr = User::findOne($user);

        if(isset($params['id']) && !$usr->isAdmin()) {
            $otherUser = User::findOne($params['id']);
            if($otherUser->isAdmin()) {
                return false;
            }
        }

        return true;
    }
```
But it seems like it always returns true, no matter what user I login as. var_dumping the ```$params``` variable always returns an empty array... so my question is, how are params passed to that variable? Am I using the rule wrong or is this a bug? I have already read the official yii2 documentation about rules

**Comment by mdmunir** [comment]
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-rules
$params value is provided from `User::can()` method.

**Comment by pc-carm** [comment]
Thanks for your response.
Tried that now, but $params is still empty, maybe I configured my rule wrong?

Here is my permission to view, update and delete users:
![image](https://cloud.githubusercontent.com/assets/5487972/7006491/291a1d40-dc47-11e4-81e3-b5c7d90ce313.png)
------------------------------------------------------------|------------------------------------------------------------------------------
Here is my rule configured through yii2-admin:
![image](https://cloud.githubusercontent.com/assets/5487972/7006519/6e5d6aa6-dc47-11e4-9424-236a6a425bf5.png)
------------------------------------------------------------|------------------------------------------------------------------------------
I'm passing params in my UserController with this method:
```php
    public function actionView($id)
    {
        if(Yii::$app->user->can('view-update-delete-usuarios', ['id' => $id])) {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }
```
And the code for my rule is still the same as I previously posted... Please let me know if I'm doing something wrong...

**Comment by pc-carm** [comment]
Ok sorry for double comment, but I figured out what happened... for some reason, when going to the URL /user/view?id=1 (or any other ID), the rule is checked at least twice, and the var_dump inside the rule only did its job the first time... Deleting var_dump and using debugger to see the $params contents did the trick and it works now as expected...

Thanks again and sorry for all the trouble, you can close this issue now
