### ISSUE TITLE
Using Yii2 admin with advanced template

### ISSUE THREAD

**Issue by devleaks** [mdmsoft/yii2-admin#144]
Hello,
Could you please explain how yii2-admin can be used to control both backend and frontend from a single point of control? Typically, yii2-admin is installed on the backend (admin side) to manage security.

However, on the backend, routes that appear in the route interface are backend routes only. Frontend routes do not appear in the list of routes, since both frontend and backend apps are separated.
So, do I need to have 2 separate access of yii2-admin to control each side? How can I get frontend routes in the list of routes on the backend side?

Thank you.

**Comment by mdmunir** [comment]
you can not.
