### ISSUE TITLE
Feature urlPrefix UrlRules.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [mdmsoft/yii2-admin#146]
hi @mdmunir, would be interesting if we could customize the url addresses off the module

Example:

    Backend Avanced Template: Url Backend (/admin).
    
    Original urlPrefix          Custom urlPrefix
    /admin                      /

    UrlRules:

    Original Url.               Custom Url.
    'admin/admin/assignment' => 'admin/assignment'

Can be customized ?

Thks in advance,

**Comment by mdmunir** [comment]
Yes you can. Do it manually via `urlManager`.

PS: The original url is not `admin/admin/assignment` but `admin/assignment` (`?r=admin/assignment`)
