### ISSUE TITLE
Error if the name of a role is a number

### ISSUE THREAD

**Issue by laxity7** [mdmsoft/yii2-admin#149]
If you set the name of a role to a number, then on the Role page (index.php?r=admin/role) you get wrong ids in the action links (starting from 0 and going up).
For example,
![go87mec](https://cloud.githubusercontent.com/assets/6792144/7116578/3e113288-e1fb-11e4-9e0d-f8bdea9da141.png)

**Comment by Clyff** [comment]
I cannot replicate this problem. It still happening with you @laxity7 ?

**Comment by mdmunir** [comment]
Upss... sory, i forget this issue. It should be fix whit this commit https://github.com/yiisoft/yii2/commit/bb4bed483339dd2e86bde1b17ebad8c0e21d61b2
