### ISSUE TITLE
Class yii\jui\AutoComplete not found

### ISSUE THREAD

**Issue by ardlian** [mdmsoft/yii2-admin#151]
Saat dalam local tidak ada maslah, namun saat di server produksi, mau create permission terjadi error. Class 'yii\jui\AutoComplete' not found.
Kemudian ane lihat http://www.yiiframework.com/doc-2.0/yii-jui-autocomplete.html. codenya di /permission/_Form.php saya ubah menjadi 
```
 <?= $form->field($model, 'ruleName')->widget(\yii\jui\AutoComplete::classname(), [
        'options' => [
            'class' => 'form-control',
        ],
        'clientOptions' => [
            'source' => array_keys(Yii::$app->authManager->getRules()),
        ]
    ]) ?>
```
masih error juga.. Class 'yii\jui\AutoComplete' not found.

**Comment by mdmunir** [comment]
nginstalnya pake composer atau manual. kalau manual mungkin extensi yii2-jui gak keinstall

**Comment by ardlian** [comment]
composer kang, ada.. 
![yii2-jui](https://cloud.githubusercontent.com/assets/11612840/7288643/2f75fbe6-e98f-11e4-9d45-b947cbda970b.PNG)

**Comment by mdmunir** [comment]
kalau manggil jui dari aplikasi bisa apa tidak?

**Comment by ardlian** [comment]
ndak bisa kang.. tak panggil langsung udah use yii\jui\AutoComplete ga bisa

**Comment by mdmunir** [comment]
berarti masalahnya bukan di `yii2-admin`

**Comment by ardlian** [comment]
iya betul..

**Comment by mdmunir** [comment]
mending nanya di group aja. lebih banyak yang bisa membantu

**Comment by ptrnov** [comment]
Salam kenal, masih newbe ne yii2, masih penasaran
