### ISSUE TITLE
Cara mengisi parameter $params pada method execute Rule

### ISSUE THREAD

**Issue by ipanardian** [mdmsoft/yii2-admin#153]
Saya membuat UserRule dengan name isUser. Dan sudah di assigned pada permission ChangePassword. Fungsinya untuk hanya user dengan id yg sama yg dapat merubah password. 
```$params['user']->user_id == $user```. 
Kemudian pada ```User::actionUpdate()``` saya tambahkan 
```\Yii::$app->user->can('ChangePassword', ['user' => $model])```. 
Tapi kenapa value $params selalu kosong? Thanks in advance

**Comment by mdmunir** [comment]
Ekstensi ini tidak menambah atau merubah behavior dari core Yii. Kalau fungsi dasar Yii tidak bekerja dengan baik tidak selalu karena ekstensi ini.
