### ISSUE TITLE
Use yii2-admin with yii2-advanced-template

### ISSUE THREAD

**Issue by leyestd** [mdmsoft/yii2-admin#154]
What should I pay attention, in which the file configuration

**Comment by varun7387** [comment]
You need to be careful where you add the code in the config files

I have currently set it up as follows:-
1. 'as access' to the backend and frontend config files
2. 'authManager' to common and console config files
3. 'module' only to common config

I have tried adding module only to the backend, but for some reason it does not seem to work.
So I just add it to common config file. But you have to sure that you add 'as access' to frontend as well to allow only guest pages

I hope this makes sense.

**Comment by leyestd** [comment]
thanks

**Comment by gauravparashar12** [comment]
@varun7387 as i setup the mdm admin module in backend application i cannot see the frontend routes

**Comment by mdmunir** [comment]
@gauravparashar12 No, its imposible.

**Comment by gauravparashar12** [comment]
@mdmunir Is it possible to assign routes to specific users. If, it is. Then please let me know what will be the correct way of doing the same.

**Comment by mdmunir** [comment]
@gauravparashar12 You also cannot directly assign routes to user. You must create `permision`, `permision` has `routes`, and user has `permision`.

**Comment by gauravparashar12** [comment]
@mdmunir thanks for the solution for specific route to particular user ,
but I am  stucked in a problem where i created half of my controllers in backend and half in frontend but all things can be managed by backend only please provide me the way how i can implement this or is i have to merge all controllers in one application then what is the best way ?

**Comment by fishlv2** [comment]
when I add the admin to bootstrap I get the following error:

Unknown bootstrapping component ID: admin

only works when i have 

'bootstrap' => ['log'],

any suggestion??

thanks

**Comment by firefox747** [comment]
@mdmunir concerning the backend-and-frontend-routes-problem mentioned by @gauravparashar12, how about we implement the solution from this stackoverflow post: https://stackoverflow.com/questions/32777923/get-modules-structure-in-yii2-advanced-template

In short you could get all the modules like this:
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../../../common/config/main.php'),
    require(__DIR__ . '/../../../common/config/main-local.php'),
    require(__DIR__ . '/../../../frontend/config/main.php'),
    require(__DIR__ . '/../../../frontend/config/main-local.php'),
    require(__DIR__ . '/../../../backend/config/main.php'),
    require(__DIR__ . '/../../../backend/config/main-local.php')
);
$modules = array_keys($config['modules']);

Then use this within your RouteController::getAppRoutes() method to get all routes.
$config could be a module property which is customizable for every Yii2 app structure. As a default you could revert to Yii::$app as you currently do.

Cheers

Kai

**Comment by RGTimothy** [comment]
Hi firefox747, can you explain the method you mentioned above step by step? Thank you.

**Comment by firefox747** [comment]
@RGTimothy sorry for my late reply. Was busy on other things the late months. I have uploaded a possible solution for yii2-admin and yii2-advanced-template. See https://github.com/mdmsoft/yii2-admin/pull/309

**Comment by leyestd** [comment]
@gauravparashar12     click refresh button     because  cache

**Comment by jimmylotus** [comment]
@mdmunir 
so which file should I edit to add these code? Thank you

**Comment by sihar** [comment]
I close the issue cause have similarity with [#309 ](https://github.com/mdmsoft/yii2-admin/pull/309)
