### ISSUE TITLE
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown prop erty: yii\console\ErrorHandler::errorAction'

### ISSUE THREAD

**Issue by zhangxingcun** [mdmsoft/yii2-admin#155]
D:\wamp\www\ya2>yii
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown prop
erty: yii\console\ErrorHandler::errorAction'

in D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Component.php:143

Stack trace:
#0 D:\wamp\www\ya2\vendor\mdmsoft\yii2-admin\components\AccessControl.php(106):
yii\base\Component->__get('errorAction')
#1 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\ActionFilter.php(67): mdm\admin\comp
onents\AccessControl->isActive(Object(yii\base\InlineAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\Acti
onEvent))
#3 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(A
rray, Object(yii\base\ActionEvent))
#4 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Module.php(607): yii\base\Component-
>trigger('beforeAction', Object(yii\base\ActionEvent))
#5 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Controller.php(139): yii\base\Module
->beforeAction(Object(yii\base\InlineAction))
#6 D:\wamp\www\ya2\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Cont
roller->runAction('', Array)
#7 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Control
ler->runAction('', Array)
#8 D:\wamp\www\ya2\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Mo
dule->runAction('', Array)
#9 D:\wamp\www\ya2\vendor\yiisoft\yii2\console\Application.php(137): yii\console
\Application->runAction('', Array)
#10 D:\wamp\www\ya2\vendor\yiisoft\yii2\base\Application.php(375): yii\console\A
pplication->handleRequest(Object(yii\console\Request))
#11 D:\wamp\www\ya2\yii(31): yii\base\Application->run()
#12 {main}

**Comment by zhangxingcun** [comment]
some one have solution,but not show.

http://www.yiiframework.com/forum/index.php/topic/63127-rbac-manager/

**Comment by zhangxingcun** [comment]
Can anyone help me please?

**Comment by mdmunir** [comment]
One solution, dont use `yii2-admin` for console application.

**Comment by zhangxingcun** [comment]
ok,thanks

**Comment by developer1agentcars** [comment]
Hi I find this post with the possible solution.

check github.com the yiisoft/yii2/issues/5141

yii2-admin user component must by set on application config, not in common config.

I add message:

I suppose you got this error when you were trying to migrate or to do something using the console, it is true that Yii add the class automatically in your component configuration and the user is indeed defined as such, but that only applies for applications based on a web\Application.

I also suppose you are using a custom user configuration and you added it to the config files under the common\ folder. Correct me if I am wrong!

Given that common is used by both by the console and the web part of the application, Yii is working correctly but indeed getting an invalid configuration.

Simply moving the user configuration to the config files ones under frontend (or whatever folder contains your web accessible structure) should solve the issue.
