### ISSUE TITLE
Advanced Template and migrations

### ISSUE THREAD

**Issue by varun7387** [mdmsoft/yii2-admin#158]
I have installed this module, but when I try to run "yii migrate " from console, I cannot run it.
It throws the following exception

![yii2-admin-migrate-error](https://cloud.githubusercontent.com/assets/2689509/7439821/376d7fd2-f0e1-11e4-8c1a-ff121ad88650.PNG)

But it works fine, if I remove the
'as access'  block from the config file

Can you please look into this??

**Comment by mdmunir** [comment]
as expected. `AccessControl` filter only used for web application
