### ISSUE TITLE
why I can view site/index but user->can(/site/index) return false ?

### ISSUE THREAD

**Issue by wlzyan** [mdmsoft/yii2-admin#165]
`user->can('/site/index')` return `true` when the user giving access `/site/index`
`user->can('/site/index')` return `false` when the user giving access `/site/*` ，But in fact, the user can access the page `site/index`.
why?

**Comment by mdmunir** [comment]
what you expected?

**Comment by wlzyan** [comment]
Struggle for different users according to different content, so want to detect whether the user has the corresponding access, but found `user->can()` didn't work properly.
I consider to change a method.

---------
now,I give a user access to the `site/*`, but the method `user->can('site/index') return `false`

**Comment by mdmunir** [comment]
You can extend `yii\web\User` and change method `can()` like as `mdm\admin\components\AccessControl` did.
https://github.com/mdmsoft/yii2-admin/blob/master/components/AccessControl.php#L67

**Comment by wlzyan** [comment]
View the source code i found the `AccessControl` using two methods to detect whether the user is authorized.
just like this
```php
if ($user->can('/site/index')){return true;}
if ($user->can('/site/*')){return true;}
return false;
```
So only one method may return an error results.

@mdmunir  thankyou
