### ISSUE TITLE
could not install with composer

### ISSUE THREAD

**Issue by su-xiaolin** [mdmsoft/yii2-admin#169]
php composer.phar require mdmsoft/yii2-admin "~1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mdmsoft/yii2-admin 1.0.0 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - mdmsoft/yii2-admin 1.0.1 requires yiisoft/yii2-jui ~2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - mdmsoft/yii2-admin 1.0.2 requires yiisoft/yii2-jui ~2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - mdmsoft/yii2-admin 1.0.3 requires yiisoft/yii2-jui ~2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - mdmsoft/yii2-admin 1.0.4 requires yiisoft/yii2-jui ~2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for mdmsoft/yii2-admin ~1.0 -> satisfiable by mdmsoft/yii2-admin[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mdmunir** [comment]
```
composer global require "fxp/composer-asset-plugin:1.0.0"
```
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by su-xiaolin** [comment]
thanks a lot, The perfect solution to my problem.

**Comment by Era2016** [comment]
what does 1.0.0 in "composer-asset-plugin:1.0.0" ? do i need to update to the neweset version ,so it will be adapted to any case?
