### ISSUE TITLE
Can i pass parameter with route using MenuHelper for particulater route

### ISSUE THREAD

**Issue by amit5992** [mdmsoft/yii2-admin#170]
I am pass parameter to route using MenuHelper but parameter not pass with route,
so, what can i do for this.

Thanks in Advance.

**Comment by mdmunir** [comment]
sorry... i dont get your question

**Comment by amit5992** [comment]
I want to create menu like this

```
view profile     ---->  /site/view?id=3
create profile  ----> /site/create
delete profile  -----> /site/delete
```

**Comment by mdmunir** [comment]
Yes you can, in menu `Route`, just create new route `/site/view?id=3`.

**Comment by amit5992** [comment]
How can i pass id dynamically to route
e.g
```
/site/view?id=Yii::$app->user->id
```

**Comment by mdmunir** [comment]
you cannot

**Comment by dadinugroho** [comment]
Instead of passing id dynamically, why don't you adapt the actionView to first not accepting parameter (become public function actionView() {...})

Second, get id afterwards inside actionView. By having $id = Yii::$app->user->id;

The rest of the actionView will be the same.

What do you think?

**Comment by amit5992** [comment]
I think your idea is right.
Thank you @dadinugroho
