### ISSUE TITLE
How to configure the system language?

### ISSUE THREAD

**Issue by denghp** [mdmsoft/yii2-admin#171]
How to configure the system language? 
  I try to change the Module init method'sourceLanguage'= >'zh-CN', but no effect.

**Comment by georgezim85** [comment]
For God... I can't set the module language to pt-BR... tried many ways... Is it shown on guide?

**Comment by ulissesvaquero** [comment]
just add this line in your config/web.php
$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
	'language' => 'pt-BR',
...
