### ISSUE TITLE
Adding Icon Field in Menu Module

### ISSUE THREAD

**Issue by ombapit** [mdmsoft/yii2-admin#173]
Hi, I don't see Icon field on Menu Module, can you update it?
class for icon can be from bootstrap. thanks..

**Comment by Clyff** [comment]
You can easly use the data field to pass things such as icons.

**Comment by lawmillion** [comment]
how to use data field

**Comment by Antariksa** [comment]
$callback = function($menu){
        $data = eval($menu['data']);
        return [
            'label' => $menu['name'],
            'url' => $menu['route'],
            'option' => $data,
            'icon' => $data['menu'], //heres what u want ! :+1: 
            'items' => $menu['children'],
        ];
    };
    $items = MenuHelper::getAssignedMenu(Yii::$app->user->id, null, $callback, true);

**Comment by wakasann** [comment]
[Integrating dmstr/yii2-adminlte-asset with mdmsoft/yii2-admin extension](https://www.my-yii.com/forum/topic/integrating-dmstryii2-adminlte-asset-with-mdmsoftyii2-admin-extension)
I found and use there,the icon data save at data field,like
```php
<?php
use mdm\admin\components\MenuHelper;
$callback = function($menu){
    $data = eval($menu['data']);
    return [
        'label' => $menu['name'],
        'url' => [$menu['route']],
        'option' => $data,
        'icon' => $menu['data'], 
        'items' => $menu['children'],
    ];
};

$items = MenuHelper::getAssignedMenu(Yii::$app->user->id, null, $callback, true);
 ?>
<aside class="main-sidebar">
    <section class="sidebar">
        <?php echo  dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' => $items
            ]
        ) ?>
    </section>
</aside>
```

**Comment by fullflash** [comment]
when using "fa fa-user" in data field and calling eval causes error.

exception 'yii\base\ErrorException' with message 'syntax error, unexpected 'fa' (T_STRING)' in C:\uniformserver\UniServerZ\www\yii2_adv_news\backend\themes\adminlte\layouts\main.php(357) : eval()'d code:1 Stack trace: #0 {main}
