### ISSUE TITLE
Logout from Menu: Method Not Allowed. This url can only handle the following request methods: POST.

### ISSUE THREAD

**Issue by cloudswitch** [mdmsoft/yii2-admin#178]
Hi,

I'm trying to build menu. As I don't really know yet how to combine (maybe it's not even possible)
**'items' => MenuHelper::getAssignedMenu(Yii::$app->user->id),**
with:
**'items' => [
                        ...
                        ['label' => 'Logout', 'url' => ['/user/security/logout']],
                    ],**

I'm trying to include logout functionality into menu, but I get this error:
**Method Not Allowed. This url can only handle the following request methods: POST.**

How can I add:
**'data-method'=>'post'**
to generated links?

OR: how can I combine:
**'items' => MenuHelper::getAssignedMenu(Yii::$app->user->id),**
with:
**'items' => [
                        ...
                        ['label' => 'Logout', 'url' => ['/user/security/logout']],
                    ],**

Interesting is, Yii2 debugger shows me both GET and POST empty. How can that be?
Thanks!

**Comment by mdmunir** [comment]
```php
$items = MenuHelper::getAssignedMenu(Yii::$app->user->id);
$items[] = [
    'label'=>'Logout',
    'url'=>['/user/security/logout''],
    'options'=>['data-method'=>'post'],
];
```

**Comment by cloudswitch** [comment]
Thank you very much! But interestingly I have the same issue. Can it be that yii2-user module somehow forces logout to be a GET method...?
