### ISSUE TITLE
How to use this module in backend for frontend routes?

### ISSUE THREAD

**Issue by nelo23** [mdmsoft/yii2-admin#191]
yii2-advanced-app template.
I've installed yii2-admin module in my /backend app, it works. Now I want to edit permissions only for frontend app, I use RBAC in DB for this but how to get frontend routes?

**Comment by madan3** [comment]
Use what you did in backend\config\main.php
its works

**Comment by RGTimothy** [comment]
Hi madan3, can you explain more about the method for this issue? Thanks.

**Comment by madan3** [comment]
There are many method to use,Better ask me some specific about the your problem there are many assign user permission and give permission to different user.So please notify me when you will have problem.

**Comment by pigochu** [comment]
Is it possible assign route path like "@frontend/*" or "@backend/abc" ?

**Comment by mdmunir** [comment]
> Is it possible assign route path like "@frontend/*" or "@backend/abc" ?

`route` is representasion of `<controller>/<action>`. Where `@frontend` going to?

**Comment by firefox747** [comment]
Hi @pigochu, i had something similar in mind. Possible solution: https://github.com/mdmsoft/yii2-admin/pull/309

**Comment by sihar** [comment]
I close the issue cause have similarity with [#309 ](https://github.com/mdmsoft/yii2-admin/pull/309)
