### ISSUE TITLE
migrations error

### ISSUE THREAD

**Issue by meizoev** [mdmsoft/yii2-admin#192]
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'mdm\admin\components\Configs' not found'

my config :
'aliases' => ['@mdm/admin' => '@app/ext/yii2admin',
 for example: 	'@mdm/admin' => '@app/extensions/mdm/yii2-admin-2.0.0',],
 
'modules' => ['admin' => [
'class' => 'mdm\admin\Module',
] ],

help

**Comment by mdmunir** [comment]
where you add `aliases` config?

**Comment by meizoev** [comment]
i add in  web.php file,

$config = [
       ...
      	'aliases' => [	
        '@mdm/admin' => '@app/ext/yii2admin',
        // for example: '@mdm/admin' => '@app/extensions/mdm/yii2-admin-2.0.0',	
	],
    'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
        ]
    ],	
    ...
]

**Comment by mdmunir** [comment]
thats it...
migration use console config.

**Comment by meizoev** [comment]
solved thanks
