### ISSUE TITLE
No components subdir in yii2-admin?

### ISSUE THREAD

**Issue by devleaks** [mdmsoft/yii2-admin#193]
I just composer updated and yii2-admin was bumped to 3.0 with this tarball in composer.lock:
https://api.github.com/repos/mdmsoft/yii2-admin/zipball/ce1fa6ff088f4cb9db204830ed030e3ef46c26eb

In this tarball there is no components subdir, but rather a classes subdir.

Is this normal? Do we have to adjust all our paths to classes rather than components?
Please adjust doc accordingly.

Best regards,
P.

**Comment by mdmunir** [comment]
Yes. I move `components` dir to `classes` dir. If you upgrade from 2.x, you must change namespace `mdm\admin\components` to `mdm\admin\classes`. The classes are:
`mdm\admin\components\ActionControl` -> `mdm\admin\classes\ActionControl`,
`mdm\admin\components\MenuHelper` -> `mdm\admin\classes\MenuHelper`
etc...

**Comment by mdmunir** [comment]
https://github.com/mdmsoft/yii2-admin/tree/3.master#upgrade-from-2x
