### ISSUE TITLE
yii2-admin 3.0 - Default route for menu

### ISSUE THREAD

**Issue by loveorigami** [mdmsoft/yii2-admin#196]
When I create new item for menu as `admin/default/index`, I have active url in widget menu.
But if I click by angular-js links, and next by link in menu, I have url as '/admin#' and empty page.
See image
![001](https://cloud.githubusercontent.com/assets/98164/9440171/bbdf6e9a-4a75-11e5-8fe0-0b535be2b49c.jpg)

can you add default route for url as '/admin#'

Thanks

**Comment by mdmunir** [comment]
I am unsure with this issue. Can you elaborate more?

**Comment by loveorigami** [comment]
* For managing menu I use MenuController- https://github.com/mdmsoft/yii2-admin/blob/master/controllers/MenuController.php, where I can't create route as `.../admin/`, and angular-url were kind of: `.../admin/#/assignment` etc.
* Now I have angular-url as `.../admin#/assignment` etc.
* If I click in menu (step 3 on image), I get url as `.../admin#` (step 4). After this page is empty (step 5).
* You can see it, if paste in url link as `.../admin#`

**Comment by loveorigami** [comment]
here video:
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/98164/9464069/a11acbea-4b29-11e5-903f-742c48951888.gif)

**Comment by mdmunir** [comment]
ohh.. i see. 
But, by default it should be redirect to '#/assignment' when hash is empty.
[default redirect](https://github.com/mdmsoft/yii2-admin/blob/1f4064fed9c335b7d165219b406a309f0f3055ce/views/default/index.php#L14-L16)

**Comment by loveorigami** [comment]
Thanks! I undestand... It is not important for me :).
