### ISSUE TITLE
太TM难装了

### ISSUE THREAD

**Issue by YL20181120** [mdmsoft/yii2-admin#200]
各种依赖呀,烦死了

**Comment by wonderful60** [comment]
翻墙呗~

**Comment by wlzyan** [comment]
国内速度慢是真的，没那么多依赖吧...
composer update后去看了集电视就装好了.

**Comment by fy007** [comment]
增加国内镜像 "repositories": [
        {"type": "composer", "url": "http://packagist.phpcomposer.com"},
        {"packagist": false}
    ]

**Comment by tisswb** [comment]
@fy007 加了也不行的，因为composer-asset-plugin这货装bower那块慢的要死~

**Comment by fy007** [comment]
@tisswb 我倒是一分钟左右就装好了。没碰上速度慢的问题。百M光纤

**Comment by tisswb** [comment]
@fy007 请问你是啥网络？墙内还是墙外？我被逼无奈，翻了墙，好歹可以用了

**Comment by asuper114** [comment]
没有VPN真是难呀


2015-12-21 11:20 GMT+08:00 WangBao <notifications@github.com>:

**Comment by fy007** [comment]
国内电信100M @tisswb，我又重新试了，早上 快，中午，晚上慢些，要3分钟左右才装好。

**Comment by shaoyikai** [comment]
用composer还是弄个vpn吧

**Comment by huangxiaoye** [comment]
我使用了mdmsoft-yii2-admin 但是我不想使用他自带的那些view，比如访问/admin/user/index 时我不想用他自带的默认的那个用户列表界面，我想自定义各个控制器的view 界面，怎么实现?（除了去改他的源码）
