### ISSUE TITLE
Installation on yii2 app advanced

### ISSUE THREAD

**Issue by fedemotta** [mdmsoft/yii2-admin#205]
Hi,
I am using version 3.

When you try to install this extension in the yii2 app advanced using DbManager the following exception raises in the migration command:

```
Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'
```

I am adding all the configuration in the backend/config/main.php (because it is where I need to use it) but the console has a different config file. That is why the error raises. I moved this configuration to the common config file.

My question is: I need to setup the yii2 admin configuration in the console for some reason I didn't understand (perhaps a security problem about the configuration)? Or this exception is a bug and this check should not be made?

Thanks!

**Comment by GaboGit** [comment]
In config.php you should add/change the component properties to USE database:
 'components' => [
  ......

        'authManager' => [
            'class' => 'yii\rbac\DbManager',
        ],

**Comment by fedemotta** [comment]
@GaboGit I know that. I already added it. My question is: Why this authManager configuration should be added in the console application? I didn't need it there, but the migration ask for it.

**Comment by GaboGit** [comment]
You need that config to run the proper migration process.
The migration process is a console php script that write the required database modifications in db.
You have to tell yii2 console environment that you are using Auth dbmanager to do this

**Comment by fedemotta** [comment]
I know what a migration is and the purpose of this migration.
Again, my question is:
Why this check is done in the console application? It generates the need of
this dependency in the console application for this check only!

**Comment by fedemotta** [comment]
Investigating this issue further I found that the possible bug is in the yii2 core
