### ISSUE TITLE
Yii debug disappear.

### ISSUE THREAD

**Issue by yoyhosoft** [mdmsoft/yii2-admin#219]
Hi,
When I use yii2-admin, Yii debug tool bar is gone, event if I set config as below it's will comeback.

'as access' =>[
     ....
     'allowActions' => [
            '*',
    ]  
]

Thanks

**Comment by mdmunir** [comment]
```php
'as access' => [
    ...
    'allowActions'=>['debug/*'],
]
```

**Comment by yoyhosoft** [comment]
Thanks a lot !!!
