### ISSUE TITLE
Migrations & Error in Call to undefined method app\models\User::find()

### ISSUE THREAD

**Issue by ricardocanelas** [mdmsoft/yii2-admin#22]
Hi..

I am not able to create the tables. 
- How do I create tables? .. In the 'migration' folder only has a migrate. 
- And the name of 'migration' folder should not be plural? 

php yii migrate/up --migrationPath=@vendor/mdmsoft/yii2-admin/migration 
Only migrate 'create_menu_table' 

..And..

![captura de tela 2014-06-26 as 22 16 45](https://cloud.githubusercontent.com/assets/663151/3406882/4e5672a8-fd99-11e3-814c-fcc973f1b068.png)

![error](https://cloud.githubusercontent.com/assets/663151/3406883/5423ad54-fd99-11e3-8fa0-6d6c4d5e2506.jpg)

**Comment by sree-kumar** [comment]
I am getting the  following error:
Call to undefined method mdm\admin\models\AuthItem::getDb()

in /var/www/html/basic/vendor/yiisoft/yii2/validators/UniqueValidator.php
