### ISSUE TITLE
Routes to module actions are struck through

### ISSUE THREAD

**Issue by jasonslam** [mdmsoft/yii2-admin#228]
Hi,

recently I extracted some of our code (MVC) into a separate repository which is now being loaded by the Composer Autoloader and bootstrapped into our application.

The problem is that now all the **routes to extracted controllers are struck through** and **when I remove them, they cannot be added back**. But we need fine-grained RBAC for these parts, too. So we cannot just say "admins get access to all the routes", and no one else gets access to the extracted ones.

So: How to make the Routes page (**admin/routes**) show all the routes to actions of bootstrapped modules?
The routes can still be accessed through special URL manager rules using a \<module:\\w+\> prefix.

**Comment by mdmunir** [comment]
1. `Routes page` only generated routes of registered modules.
2. You can add non registered controller via add manual.

**Comment by jasonslam** [comment]
Thanks for the quick response.
Adding routes manually is not really an option for us as we have quite a large amount of routes that are hard to manage individually.
What do you mean by "registering" a module?
Is this even possible for any other modules than the application itself? If yes, should not it be the default?

**Comment by mdmunir** [comment]
i mean module that registered via config
```php
    'modules' => [
        'module1' => ...
        'module2' => 
    ]
```
This extension cannot read module that not registered to application.

**Comment by jasonslam** [comment]
This is already the case with our application (config/web.php).

```
    'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
        ],
        'core' => [
            'class' => 'name\space\core\Module',
        ],
    ],
```

Still the routes to controller actions under `name\space\core\controllers` are not shown.

**Comment by jasonslam** [comment]
FYI this issue was related to the module being named according to the scheme `\name\space\core` instead of the required `\name\space-core`. (Composer spits a warning if there is more than one sub-namespace)
IIRC this caused https://github.com/mdmsoft/yii2-admin/blob/c06498ccca24707223170fc5212c64238db7c179/models/Route.php#L167 to break as it failed to resolve the path from the given namespace.
