### ISSUE TITLE
csrf Problems / Unable to verify your data submission.

### ISSUE THREAD

**Issue by SSiwek** [mdmsoft/yii2-admin#234]
Hi

with the latest dev-master ( I received via composer update today ) there is a csrf Problem.

	error	yii\web\HttpException:400	exception 'yii\web\BadRequestHttpException' with message 'Unable to verify your data submission.' in C:\Users\siw\workspace_neu\intranet_neu\vendor\yiisoft\yii2\web\Controller.php:110

As a quick fix I added the line

 public $enableCsrfValidation = false; 

in the file ItemController.php

with that I can  add and delete Routes to Permissions again.

regards
Sven

**Comment by mdmunir** [comment]
Are you using another template?

**Comment by SSiwek** [comment]
I use a template based on a theme I found in the net named "on-the-beach".

Previous versions of the admin tool worked just fine with that theme

And all other modules I use with that yii application do work.

**Comment by mdmunir** [comment]
Ensure you register `yii\web\YiiAsset`

**Comment by mdmunir** [comment]
Please update latest version

**Comment by SSiwek** [comment]
working again :) perfect

have a nice weekend
Sven
