### ISSUE TITLE
Class Menu, method filterParent(): take parent into account when finding Menu instance

### ISSUE THREAD

**Issue by nlrooat** [mdmsoft/yii2-admin#237]
Hi,

The filterParent() method in Menu class searches for Menu instances based on name only, but in my case this was not sufficient. For instance when I have top level menu item X and top level menu item Y. Both X and Y have a sub menu item with the same name Z, but with different routes. Now both sub menu items incorrectly get the same parent (either X or Y depending on which one is returned by the findOne() method).

To solve this problem, in filterParent() method I changed the line 
`$parent = self::findOne(['name' => $value]);` into 
`$parent = self::findOne(['name' => $value, 'parent' => $this->parent]);`

I hope this is useful for someone.

**Comment by mdmunir** [comment]
please check latest commit.

**Comment by nlrooat** [comment]
> please check latest commit.

Tested new implementation of filterParent(), it works as expected. Thanks!
