### ISSUE TITLE
Default route of module

### ISSUE THREAD

**Issue by jafaripur** [mdmsoft/yii2-admin#238]
Why your set default route to open project readme? in breadcrumber the root section redirect to readme.md page!!

**Comment by mdmunir** [comment]
because assignment is not always avaliable for admin module.
`assignment` page only avaliable if `User::$identityClass` set to `ActiveRecord` class.
You can set defaultRoute manually via config
```php
'modules' => [
    'admin' => [
        ...
        'defaultRoute' => 'assignment',
    ]
]
```

**Comment by jafaripur** [comment]
Thank you.
