### ISSUE TITLE
Migration doesn't create "User" table

### ISSUE THREAD

**Issue by ProudNoob** [mdmsoft/yii2-admin#245]
I'm using yii2 basic template
After editing config file, I migrate like the document says:
![first](http://i.imgur.com/9vyTcw6.png)
But there is no table named "user" in my database, which i created from scratch:
![second](http://i.imgur.com/2h7TaHO.png)
Then, it says that Table 'user' doesn't exist
![third](http://i.imgur.com/mMfTOqp.png)
What did I do wrong here? Or is your documentation faulty?

**Comment by ProudNoob** [comment]
If I have to create the table myself, please give me the columns and their data types

**Comment by mdmunir** [comment]
update latest version then do
```
yii migrate/redo --migrationPath=@mdm/admin/migrations
```

**Comment by ProudNoob** [comment]
Can't drop table "user" when i don't have it 
![forth](http://i.imgur.com/gSO9Trm.png)

**Comment by ProudNoob** [comment]
After creating a dummy table named "user" and running your command line, it works now. 
Still got error:  "PHP Fatal Error – yii\base\ErrorException. Class 'app\models\UserSearch' not found"

**Comment by mdmunir** [comment]
change your config
```php
'components' => [
    'user' => [
        'identityClass' => 'mdm\admin\models\User'
    ]
]
```
this config https://github.com/mdmsoft/yii2-admin/blob/master/docs/guide/configuration.md#customizing-assignment-controller only use when you **need it**

**Comment by ProudNoob** [comment]
Deleting Assignment Controller makes it normal again. Thank you for your support.
