### ISSUE TITLE
Rest api authentication

### ISSUE THREAD

**Issue by kurrata** [mdmsoft/yii2-admin#249]
You can't authenticate user with behavior yii\filters\auth\QueryParamAuth in controller because of the way filters(behaviors) work.

When multiple filters are configured for a single action, they are applied according to the rules described below:

- Pre-filtering

  - Apply filters declared in the application in the order they are listed in behaviors().
  - Apply filters declared in the module in the order they are listed in behaviors().
  - Apply filters declared in the controller in the order they are listed in behaviors().
  - If  any of the filters cancel the action execution, the filters (both pre-filters and post-filters) after it will not be applied.

- Running  the action if it passes the pre-filtering.

- Post-filtering

  - Apply filters declared in the controller in the reverse order they are listed in behaviors().
  - Apply filters declared in the module in the reverse order they are listed in behaviors().
  - Apply filters declared in the application in the reverse order they are listed in behaviors().

When request is being made it runs module behaviors that checks permissions while permissions are granted later in controller behaviors.

```php
namespace frontend\controllers;

use common\models\ar\User;
use common\models\Ipc;
use yii\filters\auth\QueryParamAuth;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\rest\Controller;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;
use yii\filters\AccessControl;

class IpcApiController extends Controller {

    public function init() {
        parent::init();
        \Yii::$app->user->enableSession = false;
        \Yii::$app->user->loginUrl = null;
    }

    public function behaviors() {
        \Yii::$app->response->format = Response::FORMAT_XML;
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'accessToken',
        ];
        return $behaviors;
    }
}
```

**Comment by mdmunir** [comment]
```php
use mdm\admin\components\AccessControl;


    public function behaviors() {
        \Yii::$app->response->format = Response::FORMAT_XML;
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'accessToken',
        ];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
        ];
        return $behaviors;
    }
```

**Comment by kurrata** [comment]
It never reaches the execution part of the controller behavior since 403 exception gets thrown in 1st loop where it checks modules

http://www.yiiframework.com/doc-2.0/yii-base-controller.html
```php
    public function runAction($id, $params = [])
    {
        $action = $this->createAction($id);
        if ($action === null) {
            throw new InvalidRouteException('Unable to resolve the request: ' . $this->getUniqueId() . '/' . $id);
        }

        Yii::trace('Route to run: ' . $action->getUniqueId(), __METHOD__);

        if (Yii::$app->requestedAction === null) {
            Yii::$app->requestedAction = $action;
        }

        $oldAction = $this->action;
        $this->action = $action;

        $modules = [];
        $runAction = true;

        // call beforeAction on modules
        foreach ($this->getModules() as $module) {
            if ($module->beforeAction($action)) {
                array_unshift($modules, $module);
            } else {
                $runAction = false;
                break;
            }
        }

        $result = null;

        if ($runAction && $this->beforeAction($action)) {
            // run the action
            $result = $action->runWithParams($params);

            $result = $this->afterAction($action, $result);

            // call afterAction on modules
            foreach ($modules as $module) {
                /* @var $module Module */
                $result = $module->afterAction($action, $result);
            }
        }

        $this->action = $oldAction;

        return $result;
    }
```

**Comment by mdmunir** [comment]
then remove `'as access'` from config

**Comment by kurrata** [comment]
Nothing changes. I thought `'as access'` just defines what actions always pass permission validation and validation always happens.

Here is the debug log:
Guest role doesn't have access to route:
[https://imgur.com/a/3Nq5X](url)

Guest role has permissions to route:
[https://imgur.com/a/CE9R9](url)

in 2nd debug log you can see that authentication is happening after admin module has checked for permissions

**Comment by mdmunir** [comment]
are you add `mdm\admin\components\AccessControl` to your module?

**Comment by kurrata** [comment]
What do you mean?

**Comment by mdmunir** [comment]
do you attach to your module (or application) with `mdm\admin\components\AccessControl`. Looking your log, its trigered by module.

**Comment by kurrata** [comment]
I attach it thought main config file
```php
$config = [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'bootstrap' => ['admin'],
    'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
        ],
        'gridview' => [
            'class' => '\kartik\grid\Module'
        ],
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
            'defaultRoles' => ['Guest'],
        ]
    ],
];
```

**Comment by mdmunir** [comment]
How about `config/main-local.php` or `common/config`?

**Comment by kurrata** [comment]
My bad config/main-local.php still had left overs for `'as access'`. 
Now the access checking isn't happening automatically but i cant make base controllers with the behavior added 
Sorry for wasting your time

**Comment by snoywing** [comment]
@mdmunir ,I have a question ,why the code blow not work, thank you.
```
use mdm\admin\components\AccessControl;


    public function behaviors() {
        \Yii::$app->response->format = Response::FORMAT_XML;
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam' => 'accessToken',
        ];
        $behaviors['access'] = [
            'class' => AccessControl::className(),
           ‘allowActions’=>[
           'v1/user/login'
]
        ];
        return $behaviors;
    }
```
