### ISSUE TITLE
Can I set defaultRoles for authenticated user [@]

### ISSUE THREAD

**Issue by andjelko** [mdmsoft/yii2-admin#254]
Can I set defaultRoles only for authenticated user like RBAC [@] ?

How to do that?

Cheers

**Comment by mdmunir** [comment]
Why not using `yii\filters\AccessControl` ?

**Comment by andjelko** [comment]
I did so, but I was thinking there was better way to do that.

Cheers

**Comment by mdmunir** [comment]
Create new Rule
```php
<?php
namespace app\components;
use yii\rbac\Rule;

class AuthecticateRule extends Rule
{
    public $name = 'authenticate_rule';
    
    public function execute($user, $item, $params)
    {
        return !$user->getIsGuest();
    }
}
```
Add new `role` `defaultRole` or something like that. Assign to `defaultRole` route `*` and add rule `AuthecticateRule`. Use that role as `AuthManager::$defaultRoles`
