### ISSUE TITLE
3.x how to use the route like "admin/menu/index"

### ISSUE THREAD

**Issue by chonder** [mdmsoft/yii2-admin#258]
3.x is "admin#/menu".

**Comment by mdmunir** [comment]
You cannt. 3.x is SPA using angularjs. Route only work using hash format

**Comment by chonder** [comment]
3.x , the menu with yii2-admin module is "admin#/menu", and the menu nav is different.
It's a separate nav like this : 
![image](https://cloud.githubusercontent.com/assets/8869053/14665253/5c750ebe-0704-11e6-988c-1637239f5fac.png)

2.x ,the menu with yii2-admin module is in the same place(default menu layout) 
 
but the other menu that user custom save with db can't use "admin#/menu", it's not a route.

**Comment by mdmunir** [comment]
Well. I have no idea about this.
