### ISSUE TITLE
Still be able to access "/admin/*"

### ISSUE THREAD

**Issue by chonder** [mdmsoft/yii2-admin#259]
'as access' => [
            'class' => 'mdm\admin\components\AccessControl',
            'allowActions' => [
                //'admin/*',
            ]
        ],

**Comment by mdmunir** [comment]
ensure you add the config as root (not belong any child key)
```php
return [
    ...
    'as access' => [
        ...
    ]
];
```

**Comment by chonder** [comment]
advanced,`backend/config/main.php`
```php
'components' => [
        ...
        'as access' => [
            'class' => 'mdm\admin\components\AccessControl',
            'allowActions' => [
               ...
            ]
        ],
...
]
```
I set like this, but every route can be access.

**Comment by chonder** [comment]
With yii2-admin 2.x.

**Comment by mdmunir** [comment]
not belong to `components`.

**Comment by chonder** [comment]
:+1:  

It solved my problem.
Thank you very much.
