### ISSUE TITLE
Console error on Migration on mdm\admin\components\AccessControl

### ISSUE THREAD

**Issue by efureev** [mdmsoft/yii2-admin#263]
in config:
```
'as access' => [
		'class' => 'mdm\admin\components\AccessControl',
		'allowActions' => [
			'*',
		]
	],
```
do ` ./yii migrate -p=@mdm/admin/migrations`

Result: error on different types of HandlerError: Console or Web
![2016-05-05_11-43-49](https://cloud.githubusercontent.com/assets/5524684/15037690/daf2aa36-12b6-11e6-9d20-a249f8ea0f11.png)

**Comment by mdmunir** [comment]
#155
