### ISSUE TITLE
Cannot use mdm\admin\components\ItemController as ItemController because the name is already in use

### ISSUE THREAD

**Issue by ProudNoob** [mdmsoft/yii2-admin#267]
Yii2 shows "Cannot use mdm\admin\components\ItemController as ItemController because the name is already in use" error when trying to access "index.php?r=admin%2Froute". Tried to reinstall but it said it didn't need to update. ![Error page](http://i.imgur.com/pJuKONR.png).

I tried to do a search with "ItemController" in every php file, but this is the result ![This is the result](http://i.imgur.com/Drpo4b0.png). No other file than those files in vendor folder use that name.

**Comment by mdmunir** [comment]
What your version are?
they are no `ItemController.php` in folder `controllers`.
https://github.com/mdmsoft/yii2-admin/tree/master/controllers

**Comment by ProudNoob** [comment]
update to 2.x-dev fixed the issue
