### ISSUE TITLE
Question: Ability to customize views

### ISSUE THREAD

**Issue by markmarco16** [mdmsoft/yii2-admin#270]
Hello, there is the possibility of adding a parameter in the module that allows for a render to a directory with custom views?

Maybe:

<?= $this->render('@app/modules/product/_search') ?>

If you need help, I can develop this.

**Comment by mdmunir** [comment]
Why not using `theme`?

**Comment by markmarco16** [comment]
yes, but for example, if you use aminlte the position of title is include in the layout\content

![screenshot from 2016-05-23 19 55 54](https://cloud.githubusercontent.com/assets/4205973/15488086/79eebbde-211c-11e6-90b7-66832a674d65.png)

**Comment by mdmunir** [comment]
Ok go ahead.

**Comment by markmarco16** [comment]
The correct use

```php
'components' => [
...
'view' => [
    'theme' => [
        'pathMap' => [
            '@mdm/admin/views' => '@app/views/administrator',
        ]
    ]
]
...
]
```

Thank you!
