### ISSUE TITLE
is UserController can only use mdm\admin\models\searchs\User as UserSearch search model

### ISSUE THREAD

**Issue by Heier2013** [mdmsoft/yii2-admin#273]
Hi, i want to custom my **userTable** from `user` to `staff`,as you `components/Config.php` comments says i config the `@backend/config/params.php` file like below:
``` php
return [
    'adminEmail' => 'admin@example.com',
    'mdm.admin.configs' => [
         'userTable' => '{{%staff}}',
     ]
];
```

Now, my confuse is **i can't config which UserSearch model i can use** until i modify the source code,can someone help me.
Thanks!

**Comment by mdmunir** [comment]
Why not create your own controller?

**Comment by mdmunir** [comment]
Why not create your own controller?

**Comment by Heier2013** [comment]
Thanks, I was lost in thought circles......
