### ISSUE TITLE
how to restrict guest access /admin/*

### ISSUE THREAD

**Issue by shyandsy** [mdmsoft/yii2-admin#280]
I wanna the guest can only access /admin/user/login
and admin can access other part under /admin

I created two roles: guest and admin, and the admin has permission to access the /admin/*

![image](https://cloud.githubusercontent.com/assets/5271457/16437116/ab384232-3d69-11e6-8db8-928de25f7c9a.png)
![image](https://cloud.githubusercontent.com/assets/5271457/16437124/b4356018-3d69-11e6-8a72-6b31ead21b90.png)
![image](https://cloud.githubusercontent.com/assets/5271457/16437138/c4e06156-3d69-11e6-8410-911163ab5353.png)
![image](https://cloud.githubusercontent.com/assets/5271457/16437142/cd0d4b5a-3d69-11e6-826d-50fd99c4a5ed.png)
![image](https://cloud.githubusercontent.com/assets/5271457/16437153/e2932454-3d69-11e6-93c6-d19a7a959e57.png)

my main.php
````
'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
        ],

       ......................

        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false, //使用restful时候，此参数必须为false，否则会404
            'showScriptName' => false,
            'rules' => [
                ['class' => 'yii\rest\UrlRule', 'controller' => 'user'],
            ],
        ],
        'authManager' => [
            'class' => 'yii\rbac\DbManager', // 使用数据库管理配置文件
            'defaultRoles' => ['guest'],//添加此行代码，指定默认规则为 'guest'
        ],
        'as access' => [
            'class' => 'mdm\admin\components\AccessControl',
            'allowActions' => [
                'site/*',//允许访问的节点，可自行添加
                'admin/user/login', //允许登录
                //'admin/*',//允许所有人访问admin节点及其子节点
            ]
        ],
    ],


    'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
            'layout' => 'left-menu',//yii2-admin的导航菜单
        ]
    ],
````

why the gust still can access /admin/*???

**Comment by mdmunir** [comment]
wrong place of `as access`. Not belong of `components`

**Comment by shyandsy** [comment]
@mdmunir  so where should I put this?

**Comment by mdmunir** [comment]
read this https://github.com/mdmsoft/yii2-admin/blob/master/docs/guide/configuration.md#basic-configuration
