### ISSUE TITLE
Frontend / Backend / Common Access problem

### ISSUE THREAD

**Issue by robov** [mdmsoft/yii2-admin#282]
your module works really nice.
I implemented in my frontend modules and backend modules and it works amazing.
However in my backend I have a reference to a global module (not in the path of backend), that route is not available, In my backend I open a users module located in /module/users
and I get access denied.
However when I open the same module from the frontend the access is granted.

...
    'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'allowActions' => [
            //'site/*',
            '/*',
...

- frontend
- backend
- module
--- users

**Comment by mdmunir** [comment]
remark `as access` config and then access again your `/module/users`. what do you get?

**Comment by robov** [comment]
thanks for you speedy reply
When I have this in my backend main:

`
    'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'allowActions' => [
            'site/*',
            'user/*',
            '/*',
            '*',
`
I still have the problem

**Comment by robov** [comment]
Ok, I guess I tracked it down to be not related to your marvelous work...
Sorry for bugging you...
