### ISSUE TITLE
Whitelist Rbac route

### ISSUE THREAD

**Issue by robov** [mdmsoft/yii2-admin#286]
Apparently using the RBAC module skips the ACF exceptions
When I set my config to 
```
    'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'allowActions' => [
            '/sitemap',
```
My sitemap is not available, only when I add that the the guest user role.
Is there a way to hardcode certain access routes to be open to all ?

Certain routes I want hardcoded to be accessed by all in order to not forget to set those routes.,

**Comment by robov** [comment]
The accesscontrol , public function beforeAction($action)
does not check the allowActions settings

**Comment by mdmunir** [comment]
try `'/sitemap/*'` or `'/sitemap/index'`. Ensure all `routes` are saved to db (in `admin/route` menu, all routes are in the right listbox).

**Comment by robov** [comment]
I tried all these... nothing worked

```
        'allowActions' => [
            '/sitemap',
            '/sitemap/*',
            '/sitemap/index/*',
            '/sitemap/index',
```
==> "Ensure all routes are saved to db "
Yes. When I do that it works !
BUT... I want to hardcode those allowed routes... when I do that in the DB I might forget...

**Comment by mdmunir** [comment]
> BUT... I want to hardcode those allowed routes... when I do that in the DB I might forget...

Well... this ext work using `authManager` (role, permission, etc, etc). So, to make it work, the route should be exists in `authManager` (route is treated as permission).

**Comment by robov** [comment]
Ok, maybe as a feature-request for a next release... implementing a whitelist of routes
Thanks for your support

**Comment by mdmunir** [comment]
Unsure but try this
```php
'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'except' => [
            'sitemap/*',
        ]
]
```

**Comment by robov** [comment]
Thanks for the suggestion, but that did not work either.
My current solution is to have a big warning box if there are certain permissions missing in my RBAC overview screen
