### ISSUE TITLE
getting unknown property: mdm\admin\models\searchs\User::status

### ISSUE THREAD

**Issue by fullflash** [mdmsoft/yii2-admin#287]
getting unknown property: mdm\admin\models\searchs\User::status

error happens when trying to access admin/user
did all migrations inside docs
what is the problem ? i don't see status column in user table too

**Comment by mdmunir** [comment]
what page where you access?

**Comment by fullflash** [comment]
**error happens when trying to access admin/user**

**Comment by fullflash** [comment]
i have yii2 user module too. i guess there is conflict 
'user' => [
            'class' => 'dektrium\user\Module',
        ],

**Comment by mdmunir** [comment]
> i have yii2 user module too. i guess there is conflict

make sense. dektrium user is more better user administrator. You can disable `admin/user` by set menu as `null`
```php
'modules' => [
    'admin' => [
        'class' => 'mdm\admin\Module',
        'menus' => [
            'user' => null,
        ]
    ]
]
```

**Comment by fullflash** [comment]
thanks
