### ISSUE TITLE
route problem when creating menu

### ISSUE THREAD

**Issue by fullflash** [mdmsoft/yii2-admin#288]
autocomplete not working as shown in this picture.
also got error route not found when trying to insert a simple route
admin/role (/admin/role and /admin/role/* also tried)

https://github.com/mdmsoft/yii2-admin/raw/master/docs/images/image10.png

i alsoe assigned route in route menu but still not got autocomplete or validation

![admin routes](https://cloud.githubusercontent.com/assets/19576508/17333302/eb1b9cb6-58e2-11e6-8627-891c0256bbd9.png)

![admin create menu](https://cloud.githubusercontent.com/assets/19576508/17333366/284045ec-58e3-11e6-935c-824f74cc1c1d.png)

**Comment by mdmunir** [comment]
Add all routes to the right side.

**Comment by fullflash** [comment]
Thanks.
 it would be better to drop a comment in readme about that.
