### ISSUE TITLE
problem with updateOwnPost 

### ISSUE THREAD

**Issue by fullflash** [mdmsoft/yii2-admin#290]
Hi,
i have created AuthorRule under backend\rules with namescape backend\rules
with public $name="authorRule"; inside class and overriding execute as described in official guide.

in yii2 admin create a rule with name: **authorRule**  and classname: **backend\rules\AuthorRule**

added this rule to permission **updateOwnNews**
updateOwnNews is a parent of **updateNews** permission as described in official docs.
updatePost permission has route _/news/update_

there is a role **author** with updateOwnNews permission

but user with this author role update post that not created by him.
 On debugmode breakpoint in _execute_ method just don't triggered.
Rule class just not executed.
what is wrong ?

![adminlte updatenews](https://cloud.githubusercontent.com/assets/19576508/17403769/3becd898-5a6a-11e6-8925-932389ef3b3b.png)
![adminlte authorrule](https://cloud.githubusercontent.com/assets/19576508/17403772/3bfded90-5a6a-11e6-86f0-21cad8668591.png)
![adminlte author](https://cloud.githubusercontent.com/assets/19576508/17403771/3bf9fadc-5a6a-11e6-8ef2-c74f1559e56a.png)
![adminlte updateownnews](https://cloud.githubusercontent.com/assets/19576508/17403770/3bf13438-5a6a-11e6-947c-532f7d949c0c.png)

**Comment by fullflash** [comment]
sorry my mistake. i have commented **as access** in config during some testing.

but i think this post with screens would be helpfull who has trouble with rules integration in yii2 admin.

Thanks for this excellent module by the way.

**Comment by fullflash** [comment]
how we can post a variable to **$params** attrbute ?
manually as in yii2 official rbac docs or there is some options in yii2 admin setting to data field or bizrule module ?

 ```
public function execute($user, $item, $params)
    {
//        return false;
        return isset($params["news"]) ? $params["news"]->created_by==$user : false;
    }
```

**Comment by fullflash** [comment]
changed rule now it works model id passed by **$params** function argument is enough )
```
public function execute($user, $item, $params)
    {
        $news_id = $params["id"];
        $data = News::find()->select("created_by")->where(["id"=>$news_id])->limit(1)->asArray()->one();
        return isset($data) ?  $user==$data["created_by"] : false;
    }
```

**Comment by mutahirshah** [comment]
Hi, @fullflash I have trouble in using RULE in this package can you give a clear demo example with code showing how to create a rule and after creating the rule then how to use it in coding. I need a complete example because I tried it very much but I am fail to implement it specially the $param and then calling the rule in code , I think you may be clear with my problem as from you posts it show that you have faced this problem and I think my problem is similar to yours.
Thanks.
