### ISSUE TITLE
Url in Menu is messed up

### ISSUE THREAD

**Issue by mbraidy** [mdmsoft/yii2-admin#294]
Recently, I am getting the menu in the RBAC Manager yielding wrong URL; 
e.g. I am getting  `/admin#!/assignment#%2Fmenu` instead of `/admin#/menu`.  the string _**!/assignment#**_ is inserted everywhere. 

Even when I launch the application with  `/admin#/assignment`, the URL is changed to `/admin#!/assignment#%2Fassignment` and the browser is directed to the **assignment** page.

I am using version 3.2

Is this a server setting issue or a yii2-admin one?
Thank you

**Comment by mdmunir** [comment]
version 3.x is not maintened yet. please revert to 2.x

**Comment by mbraidy** [comment]
I reverted to 2.7
thank you
