### ISSUE TITLE
Missing required parameter "id" when instantiating

### ISSUE THREAD

**Issue by pkrupald024** [mdmsoft/yii2-admin#295]
Error : Missing required parameter "id" when instantiating "budyaga\cropper\actions\UploadAction".

Configure budyaga cropper extension but generate this error. 
so please help me.

![capture](https://cloud.githubusercontent.com/assets/19386147/17580433/35cd55da-5fbc-11e6-99c3-a64983725e1c.PNG)

**Comment by mdmunir** [comment]
Why not submit issue to that extension?

**Comment by pkrupald024** [comment]
"budyaga/yii2-cropper": "*"
