### ISSUE TITLE
Available misspelled

### ISSUE THREAD

**Issue by firefox747** [mdmsoft/yii2-admin#307]
Hi,
it seems you misspelled "available" throughout our code. All i could find is "avaliable".
Doesn't hurt the functionality the way it is now. Just think it is nicer when spelled correctly.

Cheers.

**Comment by firefox747** [comment]
Also:
recrusive -> recursive

**Comment by mdmunir** [comment]
:+1: :grin: 
please submit PR

**Comment by firefox747** [comment]
There you go.
https://github.com/mdmsoft/yii2-admin/pull/308

**Comment by mdmunir** [comment]
merged :+1:
