### ISSUE TITLE
Version 3 with angular can not be installed via composer

### ISSUE THREAD

**Issue by xbzbing** [mdmsoft/yii2-admin#322]
version 3 required `"deesoft/yii2-angular": "~1.3",`,  and `deesoft/yii2-angular` required `bower-asset/angular-resource`,   and `bower-asset/angular-resource` has more than [3600 releases](https://github.com/angular/bower-angular-resource/releases).

composer costed more than 15G RAM to install these dependencies and the system hanged for almost half an hour .

so I have to choose version 2.

Is there any plan about new version?

**Comment by Code-Zilla** [comment]
how did you resolve it?
