### ISSUE TITLE
Can't add new auth item

### ISSUE THREAD

**Issue by shoxabbos** [mdmsoft/yii2-admin#345]
![image](https://user-images.githubusercontent.com/8403807/28813884-96f194ce-76b4-11e7-915b-7bc7ef9c521d.png)

**Comment by Shoxabbos** [comment]
![image](https://user-images.githubusercontent.com/8403807/28814050-6be2c98c-76b5-11e7-864b-eb0d2e50dd01.png)

Conflict with yii2 validator.
Renamed unique function all works.

**Comment by Shoxabbos** [comment]
Please fix this error!

**Comment by labmonkey** [comment]
It's because of this change in yii framework https://github.com/yiisoft/yii2/commit/8ae2223c6a50eda8534ea187357df1a167b65cdd
