### ISSUE TITLE
error on create role in yii2.12

### ISSUE THREAD

**Issue by Masyhudi** [mdmsoft/yii2-admin#356]
PHP Warning – yii\base\ErrorException
Missing argument 1 for mdm\admin\models\AuthItem::find(), called in /var/www/xyz_app/vendor/yiisoft/yii2/validators/UniqueValidator.php on line 210 and defined

**Comment by Masyhudi** [comment]
sorry, same issue..
fixed in #346

**Comment by mdmunir** [comment]
#346
