### ISSUE TITLE
The table does not exist: {{%user}}

### ISSUE THREAD

**Issue by rosancoderian** [mdmsoft/yii2-admin#387]
i got this error when accessing admin/user after installing the extension

**Comment by freddokresna** [comment]
just create table on database 

or run below script , hope this help

 
create table `user`
(
    `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` varchar(32) NOT NULL,
    `auth_key` varchar(32) NOT NULL,
    `password_hash` varchar(256) NOT NULL,
    `password_reset_token` varchar(256),
    `email` varchar(256) NOT NULL,
    `status` integer not null default 10,
    `created_at` integer not null,
    `updated_at` integer not null
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
