### ISSUE TITLE
Error on php7.2

### ISSUE THREAD

**Issue by Masyhudi** [mdmsoft/yii2-admin#392]
For compatibiliy with PHP 7.2 which does not allow classes to be named Object anymore, we needed to rename yii\base\Object to yii\base\BaseObject.

i found you use yii\base\Object in models/Assignment.php, models/Route.php and components/Configs.php.
it's fix when i change parents of three class above to yii\base\BaseObject.

**Comment by joetwostep** [comment]
I'm having the same problem.  I see the code was fixed here in github but when I run composer update on my machine it doesn't update my code to this new version.  I have "mdmsoft/yii2-admin": "~2.0" required in my composer.json file, do I need to change this?

**Comment by chriswongxp** [comment]
require mdmsoft/yii2-admin '2.x-dev'

**Comment by jarvizub** [comment]
Can you please add this change to a stable version for production?  

Thank you in advance.

**Comment by hoybin** [comment]
大哥,能不能修复一下稳定版???

**Comment by curtis18** [comment]
It is required to change Object to BaseObject for the following files. 

vendor\mdmsoft\yii2-admin\components\Configs.php
vendor\mdmsoft\yii2-admin\models\Assignment.php
vendor\mdmsoft\yii2-admin\models\Route.php

**Comment by sihar** [comment]
fix in [version 2.9](https://github.com/mdmsoft/yii2-admin/releases/tag/2.9)
