### ISSUE TITLE
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\ErrorHandler::errorAction'

### ISSUE THREAD

**Issue by thinkwcz** [mdmsoft/yii2-admin#393]
I have a problem
$ ./yii migrate --migrationPath=@mdm/admin/migrations
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\ErrorHandler::errorAction'

in F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Component.php:154

Stack trace:
#0 F:\jysoft.www\web.bbs\app\vendor\mdmsoft\yii2-admin\components\AccessControl.php(98): yii\base\Component->__get('errorAction')
#1 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\ActionFilter.php(73): mdm\admin\components\AccessControl->isActive(Object(yii\base\InlineAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#3 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Component.php(627): call_user_func(Array, Object(yii\base\ActionEvent))
#4 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Module.php(700): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Controller.php(145): yii\base\Module->beforeAction(Object(yii\base\InlineAction))
#6 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Controller.php(148): yii\base\Controller->runAction('', Array)
#7 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('', Array)
#8 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#9 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#10 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 F:\jysoft.www\web.bbs\app\yii(23): yii\base\Application->run()
#12 {main}

why?
My Environment: php7.1.13 yii2-app-advanced 2.0.14 mdmsoft/yii2-admin "~2.0"

**Comment by dimegalev** [comment]
@thinkwcz Have you solved this?

**Comment by thinkwcz** [comment]
@dimegalev  yes,config wrong.

**Comment by dimegalev** [comment]
@thinkwcz figured it out myself, thanks anyway. :)

**Comment by Er-Kalpesh** [comment]
@dimegalev whats the solution here?

**Comment by jamshiddin** [comment]
Note: If you are using yii2-basic-app template, there is a config/console.php configuration file where the authManager needs to be declared additionally to config/web.php. In case of yii2-advanced-app the authManager should be declared only once in common/config/main.php.

**Comment by ProofOfRight** [comment]
Have 

> I have a problem $ ./yii migrate --migrationPath=@mdm/admin/migrations Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\ErrorHandler::errorAction'
> 
> in F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Component.php:154
> 
> Stack trace: #0 F:\jysoft.www\web.bbs\app\vendor\mdmsoft\yii2-admin\components\AccessControl.php(98): yii\base\Component->__get('errorAction') #1 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\ActionFilter.php(73): mdm\admin\components\AccessControl->isActive(Object(yii\base\InlineAction)) #2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent)) #3 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Component.php(627): call_user_func(Array, Object(yii\base\ActionEvent)) #4 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Module.php(700): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent)) #5 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Controller.php(145): yii\base\Module->beforeAction(Object(yii\base\InlineAction)) #6 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Controller.php(148): yii\base\Controller->runAction('', Array) #7 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('', Array) #8 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array) #9 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array) #10 F:\jysoft.www\web.bbs\app\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #11 F:\jysoft.www\web.bbs\app\yii(23): yii\base\Application->run() #12 {main}
> 
> why? My Environment: php7.1.13 yii2-app-advanced 2.0.14 mdmsoft/yii2-admin "~2.0"

I have a same error
