### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by santhika29** [mdmsoft/yii2-admin#413]
saya bru saja memasang yii2-admin 2.9 via composer... ketika saya mengakses admin muncul penampakan seperti di gambar ini
![image](https://user-images.githubusercontent.com/3783522/48992487-eaa44500-f172-11e8-9042-cedfedca78f1.png)

untuk info tambahan saya menggunakan xampp dengan rincian : 

Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.10
Yii Framework/2.0.16-dev

berikut penampakan debugger nya : 
![image](https://user-images.githubusercontent.com/3783522/48992543-33f49480-f173-11e8-897d-e394b44ec396.png)

**Comment by yohantoro** [comment]
Coba cek sini bang. Semoga membantu.
[https://github.com/mdmsoft/yii2-admin/issues/392](url)

**Comment by yohantoro** [comment]
Coba cek di sini bang. Semoga membantu.

[`https://github.com/mdmsoft/yii2-admin/issues/392#issue-328909612`](https://github.com/mdmsoft/yii2-admin/issues/392#issue-328909612)
