### ISSUE TITLE
actionActivate($id), but no actionDeactivate($id) in UserController

### ISSUE THREAD

**Issue by CrazyHenk44** [mdmsoft/yii2-admin#445]
Hi, 

After activating the user, there is only the option to Delete the user, but I wonder why. Deleting is not always wanted, as that destroys any references to that user in other places.

Why is there not a actionDeactivateUser() in the UserController. Seems pretty straightforward.
If I would add it, would the patch be accepted, or am I missing a bit of the concept?

Best,

Tom

**Comment by tomalbers** [comment]
Ping

**Comment by tomalbers** [comment]
ping

**Comment by CrazyHenk44** [comment]
Ok, project is dead then. Fine. Closing.
