### ISSUE TITLE
no i18n for chinese

### ISSUE THREAD

**Issue by TTKEN** [mdmsoft/yii2-admin#448]
![image](https://user-images.githubusercontent.com/66815206/93665896-a05d2800-faac-11ea-9f07-a33b413bb3c3.png)

**Comment by TTKEN** [comment]
version:dev-master

**Comment by TTKEN** [comment]
![image](https://user-images.githubusercontent.com/66815206/93667331-ab698580-fab7-11ea-9657-d2e33e463457.png)

has some files no translate

**Comment by phpyii** [comment]
@TTKEN 你可以提交pr翻译下  第一个中文翻译版本时我提交的  好久没用这个了
