### ISSUE TITLE
Access control on master 

### ISSUE THREAD

**Issue by gilbertoteles** [mdmsoft/yii2-admin#471]
On components/AccessContol LINE: 130 there is a wrong code: $route = rtrim(string)$route, "*");
mus be like that: $route = rtrim((string)$route, "*");

**Comment by wa1kb0y** [comment]
related PR https://github.com/mdmsoft/yii2-admin/pull/472

**Comment by sihar** [comment]
Thanks for the report. Issue solved using [this PR](https://github.com/mdmsoft/yii2-admin/pull/472)
