### ISSUE TITLE
Syntax error on file mdmsoft/yii2-admin/components/AccessControl.php

### ISSUE THREAD

**Issue by bot209** [mdmsoft/yii2-admin#473]
![image](https://user-images.githubusercontent.com/92056568/194327459-3ab8349c-bfa6-4e53-9e47-214ae60ce946.png)

Need to add an opening bracket before the string. Package version 2.12.

**Comment by mtangoo** [comment]
This error is not fixed yet!
I wonder why, being such a simple thing to do.

**Comment by mtangoo** [comment]
duplicate of #471

**Comment by sihar** [comment]
thanks for the report. Issue solved using [this PR](https://github.com/mdmsoft/yii2-admin/pull/472)
