### ISSUE TITLE
'Cannot use yii\base\Object as Object because 'Object' is a special class name'

### ISSUE THREAD

**Issue by fat2fast** [mdmsoft/yii2-admin#485]
## I get error when run command

`yii migrate --migrationPath=@mdm/admin/migrations`

## Detail Error :

` PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in /app/vendor/mdmsoft/yii2-admin/classes/Configs.php on line 9`

`PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use yii\base\Object as Object because 'Object' is a special class name'`

### My version is :
- php : 8.1
- yiisoft/yii2 : 2.0.50
- mdmsoft/yii2-admin : 3.2.0

**Comment by sihar** [comment]
Version 3.* is not used for production. 
Please use version 2.*
Thanks for reporting

**Comment by ghost** [comment]
Beste,

Ik ben afwezig tot 29 juli. Neem voor dringende zaken contact op met ***@***.*** Deze mail wordt niet gelezen. 

Met vriendelijke groet,

Remco de Gronckel
