### ISSUE TITLE
Error: Unable to locate message source for category 'rbac-admin'.

### ISSUE THREAD

**Issue by m0zart89** [mdmsoft/yii2-admin#67]
After updating Yii i get this error "Unable to locate message source for category 'rbac-admin'.". Yii2-admin is also already updated.

**Comment by Rodgers2015** [comment]
can anyone help me here please


PHP User Error – yii\base\ErrorException

Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Unable to locate message source for category 'usr'.' 

in C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\i18n\I18N.php:200

Stack trace:
#0 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\i18n\I18N.php(88): yii\i18n\I18N->getMessageSource('usr')
#1 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\BaseYii.php(501): yii\i18n\I18N->translate('usr', 'New password', Array, 'en-US')
#2 C:\xampp\htdocs\mooxle\vendor\nineinchnick\yii2-usr\models\BasePasswordForm.php(101): yii\BaseYii::t('usr', 'New password')
#3 C:\xampp\htdocs\mooxle\vendor\nineinchnick\yii2-usr\models\LoginForm.php(68): nineinchnick\usr\models\BasePasswordForm->attributeLabels()
#4 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\Model.php(509): nineinchnick\usr\models\LoginForm->attributeLabels()
#5 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2-bootstrap\ActiveField.php(403): yii\base\Model->getAttributeLabel('username')
#6 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2-bootstrap\ActiveField.php(176): yii\bootstrap\ActiveField->renderLabelParts()
#7 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\widgets\ActiveField.php(165): yii\bootstrap\ActiveField->render()
#8 C:\xampp\htdocs\mooxle\views\site\login.php(27): yii\widgets\ActiveField->__toString()
#9 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\View.php(325): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\xampp\\htdocs...', Array)
#11 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, Object(app\controllers\SiteController))
#12 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\Controller.php(378): yii\base\View->render('login', Array, Object(app\controllers\SiteController))
#13 C:\xampp\htdocs\mooxle\controllers\SiteController.php(82): yii\base\Controller->render('login', Array)
#14 [internal function]: app\controllers\SiteController->actionLogin()
#15 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('login', Array)
#18 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction('site/login', Array)
#19 C:\xampp\htdocs\mooxle\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 C:\xampp\htdocs\mooxle\web\index.php(12): yii\base\Application->run()
#21 {main}
