### ISSUE TITLE
Class mdm\admin\Module does not exist

### ISSUE THREAD

**Issue by realtebo** [mdmsoft/yii2-admin#77]
I'm trying this extension for the first time

I've succesfully run composer installation of yii2-admin

In backend\config\main.php I've this (I omitted irrilevant code)

``` php
return [
    ....
    'modules' => [
        'admin' => [
            'class' => 'mdm\admin\Module',
        ]
    ],
    'components' => [
        .... 

        'authManager' => [
            'class' => 'yii\rbac\DbManager', // or use 'yii\rbac\PhpManager'
        ],
        'as access' => [
            'class' => 'mdm\admin\components\AccessControl',
            'allowActions' => [
                'admin/*', // add or remove allowed actions to this list
            ]
        ],
    ],
    ...
];
```

Also, I've enabled pretty url (this is already working)

When  I go to http://<domain>/admin 

I got this Exception

```
Class mdm\admin\Module does not exist
```

What have I forgot / mistaken?

**Comment by bondaf** [comment]
Hi!
I installed yii2-admin via Composer and I had the same error Class mdm\admin\components\AccessControl does not exist

I solved my problem replacing string in config
I replaced
'class' => 'mdm\admin\components\AccessControl',
with
'class' => 'mdm\admin\classes\AccessControl',

**Comment by GregJPreece** [comment]
People who are having this error - please check your version numbers in composer.json. I had my Composer file set to pull "*" as the version, but the 3.x releases completely breaks compatibility, resulting in exactly the error message described here:

```
Class mdm\admin\components\AccessControl does not exist
```

To fix this, I simply changed my composer.json file's requirement from:

```
"mdmsoft/yii2-admin": "*"
```

to

```
"mdmsoft/yii2-admin": "~2.0"
```

and ran "composer update".  Please make sure you know what version you're after. If you haven't yet prepped the transition to 3.x, or are unable to, setting your version accurately may fix things for you.

**Comment by joetwostep** [comment]
@GregJPreece  thank you very much, you solved my problem.

**Comment by wakasann** [comment]
@GregJPreece Thank you very much.This is I need！

**Comment by manosl24** [comment]
Hi i added version 3.x but now showing error on 
`Setting unknown property: mdm\admin\Module::menus`

how to solve this error.
