### ISSUE TITLE
Document (better) how to use this app in advanced template

### ISSUE THREAD

**Issue by realtebo** [mdmsoft/yii2-admin#78]
When running

```
yii migrate --migrationPath=@yii/rbac/migrations
```

I got this alert

```
Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'
```

I added all the config into main.php of adavanced. 

But to make migrations working, I need to move 'authManager' config into the main of common config

Thank you for your work

**Comment by bunleo** [comment]
Hi guys,
I am using basic template but I still got this error although I added
'authManager' => [
              'class' => 'yii\rbac\DbManager', // or use 'yii\rbac\PhpManager'
        ],
to web.php file in config directory

Thank in advance

**Comment by twg-group** [comment]
you need it to the console config...

**Comment by Zarey** [comment]
russellfeeed, Thanks
