### ISSUE TITLE
Restricting Access to Module

### ISSUE THREAD

**Issue by mtangoo** [mdmsoft/yii2-admin#93]
How do I suppose to restrict that? I know I can try the Application beforeAction but its a long route.
I believe module should have a way of restricting users. I suggest to add property that limits by IDs or role something like

```
if(id_is_in_admin_array or role_is_in_roles_array)
{
    allow_access
}
else
    deny_access
```

what do you think?

**Comment by unglevan** [comment]
>Assign route to role or permission.
how can i assign?

**Comment by mtangoo** [comment]
assign what?
