### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ipppinto** [mdmsoft/yii2-admin#94]
Hi,

I have this error and I don't know why (different of issue #86)

 in /var/www/vhosts/vps101842.ovh.net/cmcintranet.ippinto.ovh/vendor/yiisoft/yii2/rbac/PhpManager.php at line 641

        $this->assignments = [];
        $this->items = [];
 
        $items = $this->loadFromFile($this->itemFile);
        $itemsMtime = @filemtime($this->itemFile);
        $assignments = $this->loadFromFile($this->assignmentFile);
        $assignmentsMtime = @filemtime($this->assignmentFile);
        $rules = $this->loadFromFile($this->ruleFile);
 
        foreach ($items as $name => $item) {  <<-- This line -->
            $class = $item['type'] == Item::TYPE_PERMISSION ? Permission::className() : Role::className();
 
            $this->items[$name] = new $class([
                'name' => $name,
                'description' => isset($item['description']) ? $item['description'] : null,
                'ruleName' => isset($item['ruleName']) ? $item['ruleName'] : null,
                'data' => isset($item['data']) ? $item['data'] : null,
                'createdAt' => $itemsMtime,
                'updatedAt' => $itemsMtime,

Thank you

**Comment by ipppinto** [comment]
This is the problem. I don't have nothing.

**Comment by FantomX1** [comment]
When I removed custom items, assignment and ruleFile paths from config, removed rbac directory and re-added configs but access right data creation put into own rbacController console command which I run, containig createRole, add, createPermission commands. Mine files got filled and in the end from 
code 
```
        mkdir(Yii::getAlias("@app/rbac"));
        $auth = Yii::$app->authManager;
        $admin = $auth->createRole('admin');
        $auth->add($admin);

        $viewOwnRequest = $auth->createPermission('viewOwnRequest');
        $auth->add($viewOwnRequest);

        $auth->addChild($admin, $viewOwnRequest);

```
resulted in
```
return [
    'admin' => [
        'type' => 1,
        'children' => [
            'viewOwnRequest',
        ],
    ],
    'viewOwnRequest' => [
        'type' => 2,
    ],
];
```
