### ISSUE TITLE
Very Bad documentation, and some errors

### ISSUE THREAD

**Issue by carlos-andres** [mdmsoft/yii2-admin#99]
Good day i try to install over a day and get a lot of errors, 

for example it not works on a yii2 basic app, and when i try to configure in advance app give me a lot of errors, really is a good development but a poor in documentation. 

![img](https://cloud.githubusercontent.com/assets/5489747/5402199/10c2ca14-8150-11e4-8203-f340c2042dd6.png)
![other](https://cloud.githubusercontent.com/assets/5489747/5402200/10d8483a-8150-11e4-82d0-cfacf4e84a24.png)

```
Yii Migration Tool (based on Yii v2.0.2-dev)

Total 1 new migration to be applied:
        m140506_102106_rbac_init

Apply the above migration? (yes|no) [no]:yes
*** applying m140506_102106_rbac_init
Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'

in C:\[path]\vendor\yiisoft\yii2\rbac\migrations\m140506_102106_rbac_init.php:28
```

**Comment by bunleo** [comment]
Hi @githubjeka 
I am using basic template but I didn't see console directory in root. whether should I create main.php file in the your path?
Thank in advance

**Comment by githubjeka** [comment]
@bunleo Config of console here https://github.com/yiisoft/yii2/blob/master/apps/basic/config/console.php for basic template

**Comment by bunleo** [comment]
@githubjeka Thank you very much
